<p style='text-align: center'><a href=https://www.biozentrum.uni-wuerzburg.de/cctb/research/supramolecular-and-cellular-simulations/>Supramolecular and Cellular Simulations</a> (Prof. Fischer)<br>Center for Computational and Theoretical Biology - CCTB<br>Faculty of Biology, University of Würzburg</p>

<p style='text-align: center'><br><br>We are looking forward to your comments and suggestions. Please send them to: <br><br></p>
    
 <p style='text-align: center'>   <a href=andreas.kuhn@uni.wuerzburg.de>andreas.kuhn@uni.wuerzburg.de</a> or <a href=sabine.fischer@uni.wuerzburg.de>sabine.fischer@uni.wuerzburg.de</a></p>

<h1><p style='text-align: center'> Introduction to Julia </p></h1>


## Functions
Functions are the backbone of every Julia programm. A function is piece of code that can be executed to solve a task. They can range from only some lines of code to whole scripts. This executable code is called by an identifier. For many general tasks Julia has built-in functions, in fact you have already used some of them. Only for complex and specific tasks you need to write your own function.

### 1. Built-in Functions
The huge amount of built-in functions in Julia covers the basic needs for programming. To call a function you need to know its identifier.

The `println()` function is our first example, as it was used several times by now.

In [1]:
println("Hello world!")

Hello world!


Besides the identifier `println()` this function needs an argument. <p style='text-align: justify;'>The argument has to be added between the brackets. This function will print its argument as the scripts output. Strings will be printed directly. In contrast, variables will not be printed themselves, instead their content is printed. 

In [2]:
v1 = [1,2]
v2 = "String"

println(v1)
println(v2)


[1, 2]
String


If `println()` is given more than one argument, the arguments are printed out in the order of their position. Therefore, these types of arguments are also called positional arguments. 

In [3]:
println(v1, v2)
println(v1,v2, "  Weißkohl ", 2)

[1, 2]String
[1, 2]String  Weißkohl 2


There are ways to integrate the content of variables into strings. You have to use `$()` infront of a variable name in your string to mark the place were the variables content should be added. 
Or you choose to do it the simple route and just put you variable in between separate strings. 

In [4]:
println("I have $(v1[2]) variables, but you can see just $(v1[1])")
println("I have" ,v1[2], "variables, but you can see just", v1[1])
println("I have " ,v1[2], " variables, but you can see just ", v1[1])



I have 2 variables, but you can see just 1
I have2variables, but you can see just1
I have 2 variables, but you can see just 1


Hint: In the second case, it can become quite tedious to take care about blank spaces in between strings as Julia does print out strings without any spaces in between them. 

 To work properly with Julia you have to learn the basic functions or at least know where to find them. A good source to find specific built-in functions is either the Julia documentation (https://docs.julialang.org/en/v1/manual/functions/), when you have an idea of the functions name/identifier. Otherwise an internet search or forums can be a great help. 

##### Opinion: We believe good google/ general internet search skills are an essential, if not one of the most important skills of being a good programmer. You should not waste your time solving the same problem again that somebody else has already solved. 

![title](3y8ca1.jpg)


In order to use the offical Julia documentation inside Julia, just add a `?` infront of the function name and hit enter.

In [5]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


This will give you a short rounddown of the function, its arguments and a few examples. 

Comment: Reading the offical documentation can be intimitating at first, as the information is often expressed in a compact manner using very technical terms. But don't worry this is normal, once you have adjusted to the style of writting/thinking and memorized the most common technical terms, you will able to comprehend almost everything by just using the documentation.  

### Example functions 
Following we will present some of the most used functions in Julia.

#### 1.1. rand()
Then rand function is a very useful function and mainly serves two purposes. Firstly, it can randomly sample an object out of a given collection. 

In [7]:
any_vec = ["hans", "dieter", 4.3, 2]
rand(any_vec)

"dieter"

You can also create the object in place with the slicing notation `:`. 

In [8]:
rand(1:10)

6

If you don't give `rand()` a collection where it can sample from it will sample uniformly distributed random `Float64` values between `0.0 - 1.0`. 

In [9]:
rand()

0.3328439932875207

You can also create an array of randomly sampled objects by providing `rand()` the dimensionality of the desired array.

In [10]:
# creating vector
randi_vec = rand(5)

5-element Vector{Float64}:
 0.9722738663738644
 0.3660307745072836
 0.47772558591747594
 0.384215267707528
 0.8757532465755166

In [11]:
# creating matrix 
randi_matrix = rand(3,4)

3×4 Matrix{Float64}:
 0.045075  0.625833  0.160257  0.183574
 0.993043  0.881405  0.852236  0.857972
 0.574138  0.815175  0.752576  0.626811

You can also create an array with objects that are sampled out of your given collection. 

In [12]:
any_randi_matrix = rand(any_vec, 5,4)

5×4 Matrix{Any}:
  "hans"     "dieter"   "dieter"  4.3
 2           "hans"     "dieter"   "hans"
  "dieter"  2          4.3         "dieter"
 2          4.3         "hans"    2
 2           "dieter"  4.3         "hans"

#### 1.2 using 
The `using` keyword is used to load additional packages for specific tasks. You have already seen`using` in the second notebook where we used the `Pkg` package to install additional packages.  


In this case we gone use the `using` keyword to load the `Random` package, which provides some additionally functionality regarding random sampling. Loading of packages only has to be done once in programm execution. Therefore, for clarity reasons, it is common practice to load all neccessary packages at the begining of a programm. 

In [14]:
using Random 

Note: If you have payed attention very closey, you might be wondering why we can load the `Random` package without prior installation through the package manager `Pkg`. This is possible because the `Random` package is part of the standard libary of `Julia`, along other useful packages like(`LinearAlgebra, Statistics,...`), which always get installed alongside base `Julia`. 

##### 1.2.1 randn() 

Now we can use some of its functions like `randn()` which works very similarly to `rand()` but returns normaly distributed random numbers (mean = 0, std = 1) instead of uniformly distributed ones.   

In [15]:
randi_norm = randn()
randi_norm

-0.6701583425016875

You can also create an array of random numbers by providing `randn()` its dimensionality.

In [16]:
randi_norm_matrix  = randn(3,4)

3×4 Matrix{Float64}:
 -0.779003   0.834881  -0.343129  1.94035
  1.47491   -1.12354   -0.928463  2.13405
  2.35803   -0.202732   0.464664  0.689928

In [17]:
randi_norm_vec = randn(5)

5-element Vector{Float64}:
 -0.4152969700575553
 -0.43970418491038954
 -0.12885812957428147
  0.04143695691361735
 -1.529970991487361

##### 1.2.2 shuffle() / shuffle!()

But the `Random` packages does not only provide functions that create random values/arrays, you can also randomize the position of values inside an array with `shuffle()` and `shuffle!()`. The difference between `shuffle()` and `shuffle!()` is that `shuffle()` creates a newly shuffled array and returns it, whereas `shuffle!()` modifies the input array and returns it.


Note: The syntax convention to differentiate mutating (`!`) from non mutating functions, is strictly followed throughout all function in the standard library of Julia. In fact you have already seen it when using the `push!()` function, which adds new elements to an already existing array.  We encourage you to strictly follow this convention in your selfwritten code as well.   

In [18]:
randi_norm_matrix2 = shuffle(randi_norm_matrix)

3×4 Matrix{Float64}:
 -1.12354   -0.343129  0.689928  1.94035
 -0.928463  -0.779003  2.35803   0.464664
 -0.202732   0.834881  2.13405   1.47491

In [19]:
any_vec

4-element Vector{Any}:
  "hans"
  "dieter"
 4.3
 2

In [20]:
shuffle!(any_vec)
any_vec

4-element Vector{Any}:
  "dieter"
 2
  "hans"
 4.3

#### 1.3 minimum() / maximum()
The functions `minimum()` and `maximum()` are able to find the smallest / shortest respectively largest / longest component of their argument, as example an array.

In [21]:
array1 = [1,2,3,4,5,6]
maximum(array1)
println("min: $(minimum(array1)), max: $(maximum(array1)) ")
array2 = ["a","bc","def","ghij"]
println("min: $(minimum(array2)), max: $(maximum(array2)) ")

min: 1, max: 6 
min: a, max: ghij 


#### 1.4 range, collect()

The `range(start =1,step = 2,stop = 10 )` function is an alias for the slimer `:` notation to create iterables. But it also provides additional functionality as instead of `stop` there can also be an `length` keyword given: `range(start = 5, step =2, length = 15 )`. 

The `collect` function creates arrays out of other collections or iterables. Together this a convient way to create arrays. 

In [22]:
println(typeof(1:10))
println(1:10)

UnitRange{Int64}
1:10


In [23]:
println(typeof(collect(1:10)))
println(collect(1:10))

Vector{Int64}
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [24]:
println()
println(collect(1:10))
println(collect(range(5,10)))
println(collect(range(start = 2, step =-0.5, length =100)))


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[5, 6, 7, 8, 9, 10]
[2.0, 1.5, 1.0, 0.5, 0.0, -0.5, -1.0, -1.5, -2.0, -2.5, -3.0, -3.5, -4.0, -4.5, -5.0, -5.5, -6.0, -6.5, -7.0, -7.5, -8.0, -8.5, -9.0, -9.5, -10.0, -10.5, -11.0, -11.5, -12.0, -12.5, -13.0, -13.5, -14.0, -14.5, -15.0, -15.5, -16.0, -16.5, -17.0, -17.5, -18.0, -18.5, -19.0, -19.5, -20.0, -20.5, -21.0, -21.5, -22.0, -22.5, -23.0, -23.5, -24.0, -24.5, -25.0, -25.5, -26.0, -26.5, -27.0, -27.5, -28.0, -28.5, -29.0, -29.5, -30.0, -30.5, -31.0, -31.5, -32.0, -32.5, -33.0, -33.5, -34.0, -34.5, -35.0, -35.5, -36.0, -36.5, -37.0, -37.5, -38.0, -38.5, -39.0, -39.5, -40.0, -40.5, -41.0, -41.5, -42.0, -42.5, -43.0, -43.5, -44.0, -44.5, -45.0, -45.5, -46.0, -46.5, -47.0, -47.5]


#### 1.5 length()
The function `length()` counts the length of an object. The argument needs to be an iterable object.

In [25]:
println(length("dieter"))
println(length([1,2,3,4]))
println(length(Dict("animal"=>"snake","number" =>7)))
println(length(1:10))

6
4
2
10


Hint: Many function can also be broadcasted (sometimes also refered to as vectorized) by the `.` operator to each element when used on a collection. The returning object is then an array with the same dimension as the object but with the return value of the function as entries.  

In [26]:
array_of_arrays = [y = [x = rand() for x in 1:rand(1:10)] for y in 1:10]

10-element Vector{Vector{Float64}}:
 [0.55325132685251, 0.1073268495084364, 0.1587092643206195, 0.7755145606779527]
 [0.09413272969536801, 0.6414922465618657, 0.18634243930871297, 0.2918996319833994, 0.299672036074629, 0.30378424320783715, 0.8230201682393146]
 [0.8596881568613798, 0.5237907209808036, 0.5733378258849645, 0.9136281563145594, 0.3938792939046748, 0.3154384333164071, 0.8178380348662705, 0.23408551229589591, 0.25018443094492615, 0.24467803017334966]
 [0.5733713262734602, 0.8659197247758901, 0.34467160599260704, 0.05493259253219662]
 [0.6186907370765858, 0.6899226337352432, 0.9597154976559985, 0.2854044455598378]
 [0.7713838080032265, 0.08964727924557514, 0.15726286985044802]
 [0.002300786930937382, 0.25196715107927203]
 [0.9546580730162463, 0.4849069573927287, 0.9758202193558612, 0.8121336722800568, 0.44865341289186145, 0.35020863831176985, 0.4991368621166976, 0.46365538698593833, 0.29832081261626175, 0.5862311308982123]
 [0.15084328872840735, 0.8947689864408734, 0.286461306

In [29]:
println(length(array_of_arrays))
println(length.(array_of_arrays))

10
[4, 7, 10, 4, 4, 3, 2, 10, 7, 8]


#### 1.6 readline()
If you need an user to type in some informations use the `readline()` function. This function will open a field to input text.

In [30]:
input = readline()

stdin>  23


"23"

If you are in Jupyter notebook you also use the `IJulia.readprompt()` function which also allows you to print out a message to the user.  

In [31]:
input = IJulia.readprompt("Please input a number")

Please input a number 123


"123"

#### 1.7 parse()
All input is interpreted as a string, in order to create Int64 or Float64 from input we can use the `parse` function. The first argument is the datatype we want to create and the second one is the string we want to parse. 

In [32]:
input = IJulia.readprompt("Please input a number")
number_input = parse(Int64,input)
println(input," ",typeof(input))
println(number_input," ",typeof(number_input))

Please input a number 13


13 String
13 Int64


#### 1.8 sort() / sort!()
To sort an iterable object you can use the function `sort()` or `sort!()`. Just add the object to sort as argument. Similar to `shuffle()` and `shuffle!()`, `sort()` creates a new array and returns it, whereas `sort!()` modifies the input array and returns it. 

In [33]:
array2 = [1,0,9,4,3,8]
println(sort(array2))
#original array is not changed
println(array2)

println(sort!(array2))
#original array is changed 
println(array2)


[0, 1, 3, 4, 8, 9]
[1, 0, 9, 4, 3, 8]
[0, 1, 3, 4, 8, 9]
[0, 1, 3, 4, 8, 9]


 #### 1.9 keyword arguments
The two `sort() /sort!()` functions also have some optional arguments so called keyword arguments. These arguments are given by calling their respective keyword and always have a default value. In contrast to positional arguments their position does not matter.  One important keyword argument for the `sort` function is `rev` which means reversed order. This can be true or false, whereas the default value is false.  

In [34]:
println(sort(array2,rev = true))

[9, 8, 4, 3, 1, 0]


In [35]:
## position of keyword argument does not matter: 
sort(array2,rev = true) == sort(rev = true,array2) 

true

Note: Even though the position of keyword arguments does not matter, it is common practice to provide them after all positional arguments. So always try to write : 
``` julia
func1( a,b,c, rev = true, hans = 10, color = "green")
```
instead of :
``` julia
func1( hans = 10, a,b,color = "green",c, rev = true)
```
as the second variant becomes very confusing very fast :). 



When we take a look at the offical documentation for sort by calling `?sort` or going to the respective webpage (https://docs.julialang.org/en/v1/base/sort/) we can see that `sort` has overall 5 keyword arguments. One of these 5 keyword arguments is called `by`. According to the documention : "The by keyword lets you provide a custom function that will be applied to each element before comparison" . The question is now how do we provide a custom function ? This leads us smoothly to the next big section in this chapter:  How to write your own function.

### 2. Self written Functions

There are three ways to define a function in Julia. 
The first, quickest and dirtiest way is to use the `->` operator:

In [36]:
firstfunc = x-> x^2

#5 (generic function with 1 method)

This is a function with the identifier `firstfunc` that operates on the input argument x and raises x to the power of 2 and returns the new value. 

There is also another more mathematical inspired way to define a function in one line by using the `identifier(argument) = operation ` syntax.

In [38]:
secondfunc(x) = x^3
#arguments can also be empty
thirdfunc() = rand(1:10)
#also multiple arguments are possible
fourthfunc(t,u) = t*u +4

fourthfunc (generic function with 1 method)

We can call these functions by their identifier together with the right number of arguments. 

In [39]:
println(firstfunc(10))
println(secondfunc(3))
println(thirdfunc())
println(fourthfunc(2,5))

100
27
10
14


#### 2.1 Anonymous functions

In [40]:
x-> x^2

#7 (generic function with 1 method)

With the `->` syntax we can even omitting the identifier. But why would you define a function without an identifier so cannot even call it ?  
These so called anonymous functions are very useful when they are used as an argument to another function.

Now, we come back to the `sort` function where we can give such an anonymous function to the `by` keyword.  

In [41]:
println(sort( ["bbb","aaaaaaaaa","cccccc"],by = x->length(x)))

["bbb", "cccccc", "aaaaaaaaa"]


##### 2.1.1 Map

The map function is another very useful function that takes a function  and a collection as arguments. The function is then applied to all elements of the collection. 

In [42]:
println(map(firstfunc,collect(1:10)))
# whe could also use the . notation to achieve the same
println(firstfunc.(collect(1:10)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


We can also apply a function to every element of a collection by using the previously shown `.` notation for broadcasting operators like `.+`. But the big advantage of the `map` function compared to the `.` notation is that we also define an anonymous function right in place.  

In [43]:
map(x->x^3+x^2+x,collect(1:10))

10-element Vector{Int64}:
    3
   14
   39
   84
  155
  258
  399
  584
  819
 1110

We can also define quite complex functions with the `->` notation. 

In [44]:
map(x->if x%3 == 0 x^3+x^2+x  elseif x%2 == 0 x =x^4 else x = 0  end,collect(1:10))

10-element Vector{Int64}:
     0
    16
    39
   256
     0
   258
     0
  4096
   819
 10000

But as seen in the cell above, it can get messy very fast when a  bigger function is defined in one line with the  `->` syntax. The same is also true for the `identifier(argument) = operation ` syntax. 

### 2.2 Complex functions

When we want to define big and complex functions we should use the third and most powerful way Julia provides us to define functions:
``` julia
function identifier(arguments,...)
    
    operations...
    
    return result,...
    
end
```



For example we can define a function in this way that adds two numbers together but only if the two numbers are even. If one or both numbers aren't even an error is printed and 0 is returned.

In [45]:
function add_only_even(num1,num2)
    
    if num1%2 ==0 && num2%2 ==0
        return num1*num2
    else
        println("ERROR ERROR ERROR")
        return 0
    end
end

add_only_even (generic function with 1 method)

In [46]:
add_only_even(2,4)

8

In [47]:
add_only_even(2,5)

ERROR ERROR ERROR


0

With this syntax it is also possible to modify the return value. E.g. we don't need to return aynthing. 

This function for example make the elements of the input array smaller when they exceeds the given max size.  

In [48]:
function make_elements_smaller!(vector,max_size)
    for i in 1:length(vector)
        if vector[i] > max_size
            vector[i] = max_size
        end
    end
end    

make_elements_smaller! (generic function with 1 method)

As we want to follow the syntax convention regarding mutating and non mutation functions, the function name ends with a `!`.  

In [49]:
test_vec = rand(1:10,10)

10-element Vector{Int64}:
 9
 7
 7
 1
 3
 3
 9
 4
 4
 6

In [50]:
#no return value
make_elements_smaller!(test_vec,5)

In [51]:
test_vec

10-element Vector{Int64}:
 5
 5
 5
 1
 3
 3
 5
 4
 4
 5

The original test_vec has been changed.

#### 2.3 Keyword arguments in own functions. 
Keyword arguments offer a possibility to provide function arguments with a default value. The argument is replaced by a keyword and a default value like this `keyword = default`. Keyword arguments have to be put after normal arguments with an `;`. The function can then be called either without argument, then the default value will be chosen, or with the number of keyarguments you need.

Note: In the documentations of many programming languages/packages it is common to use the abbreviation `args` for positional arguments and `kwargs` for keyword arguments.  

In [52]:
function make_elements_smaller2!(vector;max_size = 5)
    for i in 1:length(vector)
        if vector[i] > max_size
            vector[i] = max_size
        end
    end
end    

make_elements_smaller2! (generic function with 1 method)

In [53]:
test_vec_2 = rand(1:10,10)
test_vec_3 = rand(1:100,10) 

10-element Vector{Int64}:
 21
 83
 87
 68
 62
 99
 62
 35
 65
 42

In [54]:
#now we can either use the default value 5 of the keyword argument or change the value by using the keyword. 
make_elements_smaller2!(test_vec_2)
make_elements_smaller2!(test_vec_3, max_size = 50)

In [55]:
test_vec_2

10-element Vector{Int64}:
 3
 1
 5
 4
 3
 1
 5
 5
 2
 3

In [56]:
test_vec_3

10-element Vector{Int64}:
 21
 50
 50
 50
 50
 50
 50
 35
 50
 42

## Exercises:
Execute the following cell, to create the variables `a_1` - `a_4. `

In [61]:
a_1=[10, 39, 34, 35, 20, 32,  3,  9, 29, 35,  0, 27, 36, 40, 33,  5, 12, 24, 11, 50,  1,  7, 14, 22,  9]
a_2=[15,  2, 11, 16, 14,  1, 12, 14,  3,  7,  0,  4,  6, 13, 18, 19,  3,  9, 15, 16,  0, 19, 12, 13, 13]
a_3=[   4,   5,   1,   6,  3,  -3,  -6,  -1, -5,   -4]
a_4=["lizard","cat","mouse","bird","butterfly"];

### <p style='color: green'>easy</p>
1. Check all arrays for their length, print it and save the length of `a_1` in a variable.

2. Find the minimum and maximum of `a_1` and `a_3`, save the min and max of `a_1` in variables.


3. Print the sentence: `"A_1 is x elements long. Its maximum is x and its minimum y."` In place of `x` and `y` add the actual values. Use your saved values.

4. Sort `a_1` and `a_4`.

### <p style='color: orange'>medium</p>


5. You might have used `1:(length(array1))` in one of your loops, there is a better solution for this task. Search for the function `enumerate()`. Familiarize yourself with this function and use it to improve the following code:
````Julia
hansus = [1,5,8,2,7,8,3,2,8,2,9,7,4]
for i in 1:(length(hansus))
       println("The element with index $(i) is $(hansus[i])")
end
````

6. Write & execute a function that asks to input a number, multiplies it by `10` and prints the result. The script should ask for more input till you type in: `stop`.

Hint: If you are struggling with that problem, take a look at the number guesser in the first jupyter notebook called "Julia_Notebooks".   

7. Install the package `Distributions` so that you are able to execute the following cell. What is the difference between `rand()` and `rand(Uniform(-1,1))`?

In [64]:
using Distributions

8. Use the `scatter()` function from the `CairoMakie` ploting package and make a scatter plot with the created values for x and y below. 


In [67]:
x = collect(1:100)
y = [ (x^1.2+x*0.5rand(Uniform(-1,1))+rand(Uniform(-1,1)*5)) for x in 1:100];

Hint: The `;` at the end of the last line surpresses the output of the last variable in a cell. 

9. Add a line plot to your scatter plot with the `lines!` function that plots x and y_truth.

Hint: The lines!() function always modifies the last used plot, but does not give an output. If you want an output you should give your scatter plot a name and call it after it was modified

In [69]:
y_truth = [ x^1.2 for x in 1:100];

### <p style='color: red'>hard</p>


10. Now we have a plot containing the measured data and the ground truth but not the error.  Take a look at the documentation of Makies errorbar (https://makie.juliaplots.org/stable/examples/plotting_functions/errorbars/) and add errorbars to every plotted point of the measured data with the `errorbar!()` function.  



In [71]:
y_error = [0.5*x+5 for x in 1:100];

11. Read the section of the Julia documentation regarding `Varargs Functions` (https://docs.julialang.org/en/v1/manual/functions/#Varargs-Functions). Write your own function with variable arguments. The function should perform various calculations:
- It should take two numbers and any count of additional numbers
- It should sum up all arguments
- A switch should allow to instead multiply all arguments.
- If less then 2 numbers are provided an error message should be provided

12. Write & execute a function, that processes an array. The function should test if the array is filled with numbers or strings.
    - If the array contains only one data type, the appropriate function should be used: 
        - If it is a array of numbers, it should display the minimum and maximum
        - If it is a array of strings, use a built-in function to sort it by length.
     - If the array contains both numbers and strings (or anythingelse= an error message should be displayed.