<p style='text-align: center'><a href=https://www.biozentrum.uni-wuerzburg.de/cctb/research/supramolecular-and-cellular-simulations/>Supramolecular and Cellular Simulations</a> (Prof. Fischer)<br>Center for Computational and Theoretical Biology - CCTB<br>Faculty of Biology, University of Würzburg</p>

<p style='text-align: center'><br><br>We are looking forward to your comments and suggestions. Please send them to: <br><br></p>
    
 <p style='text-align: center'>   <a href=andreas.kuhn@uni.wuerzburg.de>andreas.kuhn@uni.wuerzburg.de</a> or <a href=sabine.fischer@uni.wuerzburg.de>sabine.fischer@uni.wuerzburg.de</a></p>

<h1><p style='text-align: center'> Introduction to Julia </p></h1>


## Functions
Functions are the backbone of every Julia programm. A function is a piece of code that can be executed to solve a task. They can range from only some lines of code to whole scripts. This executable code is called by an identifier. For many general tasks Julia has built-in functions, in fact you have already used some of them. Only for complex and specific tasks you need to write your own function.

### 1. Built-in Functions
The huge amount of built-in functions in Julia covers the basic needs for programming. To call a function you need to know its identifier.

The `println()` function is our first example, as it has been used several times by now.

In [2]:
println("Hello world!")

Hello world!


Besides the identifier `println()`, this function needs an argument. The argument has to be added between the brackets. In a JupyterNotebook `println()` will print its argument under the cell where it is executed.  Strings will be printed directly. In contrast, variables will not be printed themselves, instead their content is printed. 

In [5]:
v1 = [1,2]
v2 = "String"

println(v1)
println(v2)


[1, 2]
String


If `println()` is given more than one argument, the arguments are printed out in the order of their position. Therefore, such types of arguments are called __positional arguments__. 

In [4]:
println(v1, v2)
println(v1,v2, "  Weißkohl ", 2)

[1, 2]String
[1, 2]String  Weißkohl 2


There are two basic ways to integrate the content of variables into strings. You can either use `$()` infront of a variable name in your string. This signals Julia to transform the variables content into a string. Or you choose the simpler route and put you variable in between separate strings. 

In [6]:
println("I have $(v1[2]) variables, but you can see just $(v1[1])")
println("I have" ,v1[2], "variables, but you can see just", v1[1])
println("I have " ,v1[2], " variables, but you can see just ", v1[1])



I have 2 variables, but you can see just 1
I have2variables, but you can see just1
I have 2 variables, but you can see just 1


Comment: In the second case, it can become quite tedious to take care about blank spaces in between strings as Julia prints out strings without any spaces in between them. 

 To work properly with Julia, you have to learn the basic functions or at least know where to find them. A good source to find specific built-in functions is either the Julia documentation (https://docs.julialang.org/en/v1/manual/functions/), when you have an rough idea about the functions name/identifier or purpose. Otherwise an internet search or forums can be a great help. 

##### Opinion: We believe good google/ general internet search skills are an essential, if not one of the most important skills of being a good programmer. You should not waste your time solving the same problem again that somebody else has already solved. 

![title](3y8ca1.jpg)


In order to use the offical Julia documentation inside Julia, just add a `?` infront of the function name and hit enter.

In [7]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


This will give you a short summary of the function, its arguments and a few examples. 

Comment: Reading the offical documentation can be intimitating at first, as the information is often expressed in a compact manner using very technical terms. But don't worry, this is normal. Once you have adjusted to the style of writing/thinking and memorized the most common technical terms, you will be able to comprehend almost everything by just using the documentation.  

### Example functions 
In the following we will present some of the most used functions in Julia.

#### 1.1. rand()
The rand function is a very useful function and mainly serves two purposes. Firstly, it can randomly sample an object out of a given collection. 

In [31]:
any_vec = ["hans", "dieter", 4.3, 2]
rand(any_vec)

4.3

You can also create the object in place with the slicing notation `:`. 

In [33]:
rand(1:10)

8

If you don't give `rand()` a collection where it can sample from, it will sample uniformly distributed random `Float64` values between `0.0 - 1.0`. 

In [34]:
rand()

0.3896759279523032

You can also create an array of randomly sampled objects by providing `rand()` the dimensionality of the desired array.

In [35]:
# creating vector
randi_vec = rand(5)

5-element Vector{Float64}:
 0.48723667777443014
 0.23192498330537914
 0.04619983482502621
 0.424368145354724
 0.6949768323785054

In [36]:
# creating matrix 
randi_matrix = rand(3,4)

3×4 Matrix{Float64}:
 0.986314    0.178163  0.0729793  0.377214
 0.543387    0.22284   0.969253   0.120598
 0.00767772  0.939654  0.510572   0.666106

You can also create an array with objects that are sampled out of your given collection. 

In [37]:
any_randi_matrix = rand(any_vec, 5,4)

5×4 Matrix{Any}:
  "dieter"  4.3        2    2
  "dieter"  2          4.3   "dieter"
  "dieter"  4.3        2     "dieter"
 4.3         "dieter"  2     "dieter"
 4.3        2          2    2

#### 1.2 Random Package
The `using` keyword is used to load additional packages for specific tasks. You have already seen`using` in the second notebook.  


In this case the `Random` package is loaded, which provides additionally functionality regarding random sampling. The loading of a package needs to be done only once in programm execution. Therefore, for clarity reasons, it is common practice to load all neccessary packages at the begining of a programm/Jupyter Notebook. 

In [44]:
using Random 

Note: If you have payed attention very closey, you might be wondering why we can load the `Random` package without prior installation through the package manager `Pkg`. This is possible because the `Random` package is part of the standard libary of `Julia`, along other useful packages like(`LinearAlgebra, Statistics,...`), which are always installed alongside base `Julia`. 

##### 1.2.1 randn() 

Now you can use all the additional functions which are provided by the `Random` package. One of these is the `randn()` function, which works very similarly to `rand()` but returns normally distributed random numbers (mean = 0, std = 1) instead of uniformly distributed ones.   

In [45]:
randi_norm = randn()
randi_norm

0.8856850657653603

You can also create an array of random numbers with `randn()` by specifying the desired dimensionality.

In [48]:
randi_norm_matrix  = randn(3,4)

3×4 Matrix{Float64}:
  1.29561   1.07872    0.552664  -1.55865
 -0.40623   1.86689    1.08801    1.08348
 -0.106128  0.733178  -0.523794   0.853832

In [49]:
randi_norm_vec = randn(5)

5-element Vector{Float64}:
  0.4102728116301187
 -1.4110690010642164
  3.089283569846776
 -1.5098960024037682
  0.9304041288388034

##### 1.2.2 shuffle() / shuffle!()

The `Random` package does not only provide functions that create random values/arrays. You can also randomize the position of values inside an array with `shuffle()` and `shuffle!()`. The difference between `shuffle()` and `shuffle!()` is that `shuffle()` creates a newly shuffled array and returns it, whereas `shuffle!()` modifies the input array and returns it.


Note: The syntax convention to differentiate mutating (`!`) from non mutating functions, is strictly followed throughout all functions in the standard library of Julia. In fact, you have already seen examples like the `push!()` function, which adds new elements to an already existing array. We encourage you to strictly follow this convention in your selfwritten code as well.   

In [50]:
randi_norm_matrix2 = shuffle(randi_norm_matrix)

3×4 Matrix{Float64}:
  1.08348   1.86689    0.733178  0.853832
  1.07872  -0.106128   1.29561   0.552664
 -1.55865  -0.523794  -0.40623   1.08801

In [51]:
any_vec

4-element Vector{Any}:
  "hans"
  "dieter"
 4.3
 2

In [52]:
shuffle!(any_vec)
any_vec

4-element Vector{Any}:
  "dieter"
  "hans"
 2
 4.3

#### 1.3 minimum() / maximum()
The functions `minimum()` and `maximum()` are able to find the smallest / shortest and largest / longest component of an iterable (e.g. an array) respectively.

In [59]:
array1 = [1,2,3,4,5,6]
maximum(array1)
println("min: $(minimum(array1)), max: $(maximum(array1)) ")
array2 = ["a","bc","def","ghij"]
println("min: $(minimum(array2)), max: $(maximum(array2)) ")

min: 1, max: 6 
min: a, max: ghij 


#### 1.4 range, collect()

The `range(start =1,step = 2,stop = 10 )` function is an alias for the slimmer `:` notation to create iterables. But it also provides additional functionality as instead of `stop` there can also be an `length` keyword given: `range(start = 5, step =2, length = 15 )`. 

The `collect` function creates arrays out of other collections or iterables. Together this a convient way to create arrays. 

In [61]:
println(typeof(1:10))
println(1:10)

UnitRange{Int64}
1:10


In [62]:
println(typeof(collect(1:10)))
println(collect(1:10))

Vector{Int64}
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [63]:
println()
println(collect(1:10))
println(collect(range(5,10)))
println(collect(range(start = 2, step =-0.5, length =100)))


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[5, 6, 7, 8, 9, 10]
[2.0, 1.5, 1.0, 0.5, 0.0, -0.5, -1.0, -1.5, -2.0, -2.5, -3.0, -3.5, -4.0, -4.5, -5.0, -5.5, -6.0, -6.5, -7.0, -7.5, -8.0, -8.5, -9.0, -9.5, -10.0, -10.5, -11.0, -11.5, -12.0, -12.5, -13.0, -13.5, -14.0, -14.5, -15.0, -15.5, -16.0, -16.5, -17.0, -17.5, -18.0, -18.5, -19.0, -19.5, -20.0, -20.5, -21.0, -21.5, -22.0, -22.5, -23.0, -23.5, -24.0, -24.5, -25.0, -25.5, -26.0, -26.5, -27.0, -27.5, -28.0, -28.5, -29.0, -29.5, -30.0, -30.5, -31.0, -31.5, -32.0, -32.5, -33.0, -33.5, -34.0, -34.5, -35.0, -35.5, -36.0, -36.5, -37.0, -37.5, -38.0, -38.5, -39.0, -39.5, -40.0, -40.5, -41.0, -41.5, -42.0, -42.5, -43.0, -43.5, -44.0, -44.5, -45.0, -45.5, -46.0, -46.5, -47.0, -47.5]


#### 1.5 length(), sum(), prod()
The functions `length()`, `sum()` and `prod()` all work on iterable objects like arrays and return one value.  `length()` returns the numbers of elements, `sum()` the sum of the elements and `prod()` the product of its elements. 

In [64]:
println(length("dieter"))
println(length([1,2,3,4]))
println(length(Dict("animal"=>"snake","number" =>7)))
println(length(1:10))

6
4
2
10


In [84]:
sum(collect(1:5))

15

In [ ]:
prod(collect(1:5))

120

`sum()` and `prod()` will only work if there is common method of adding or multipling for all elements defined. 

In [87]:
sum([1,1.0,"hans"])

LoadError: MethodError: no method matching +(::Float64, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  +(::T, ::T) where T<:Union{Float16, Float32, Float64} at float.jl:383
  +(::Union{Float16, Float32, Float64}, ::BigFloat) at mpfr.jl:414
  ...

Similar to basic operators, functions can also be broadcasted (sometimes also referred to as vectorized) by the `.` operator to each element when used on a collection. The returning object is then an array with the same dimension as the object but with the return value of the function as elements.  

In [68]:
array_of_arrays = [y = [x = rand() for x in 1:rand(1:10)] for y in 1:10]

10-element Vector{Vector{Float64}}:
 [0.6925025488304911, 0.42515138881803827, 0.3585629929623382, 0.9320789709553322, 0.9251305771350714, 0.7955627086843089, 0.29856521813606474, 0.7380123948165705]
 [0.7625723365046855]
 [0.7079061608161111, 0.8873474038721944]
 [0.9735976735291757, 0.73463964462371, 0.3134859566478828, 0.8508446049266939]
 [0.9259128210310815, 0.825739975979311, 0.9820853763721366, 0.3709189098256793, 0.00034317470129374694]
 [0.7035038388451776, 0.5969456998583865, 0.025759465117949798, 0.5054149119932302]
 [0.334987183344277, 0.6479655651774753, 0.6988710096745754, 0.8306047505753344, 0.6673221149953511]
 [0.5482695369976974]
 [0.3583242302774947, 0.012785157457317009]
 [0.8017477545670803, 0.07147866492044319, 0.28673347257916226, 0.3371100430207613, 0.7289958822481278]

In [69]:
println(length(array_of_arrays))
println(length.(array_of_arrays))

10
[8, 1, 2, 4, 5, 4, 5, 1, 2, 5]


#### 1.6 readline()
If you want an user to input some information use the `readline()` function. This function will open a field to input text.

In [73]:
input = readline()

stdin>  23


"23"

If you are using a Jupyter notebook you also use the `IJulia.readprompt()` function thatallows you to print out a message to the user at the same time.  

In [75]:
input = IJulia.readprompt("Please input a number")

Please input a number 34


"34"

#### 1.7 parse()
All input is interpreted as a string. In order to create `Int64` or `Float64` values from the input, you can use the `parse` function. The first argument is the datatype we want to create and the second one is the string we want to parse. 

In [82]:
input = IJulia.readprompt("Please input a number")
number_input = parse(Float64,input)
println(input," ",typeof(input))
println(number_input," ",typeof(number_input))

Please input a number 23


23 String
23.0 Float64


#### 1.8 sort() / sort!()
To sort an iterable object, you can use the function `sort()` or `sort!()`.  Similar to `shuffle()` and `shuffle!()`, `sort()` creates a new array and returns it, whereas `sort!()` modifies the input array and returns it. 

In [84]:
array2 = [1,0,9,4,3,8]
println(sort(array2))
#original array is not changed
println(array2)

println(sort!(array2))
#original array is changed 
println(array2)


[0, 1, 3, 4, 8, 9]
[1, 0, 9, 4, 3, 8]
[0, 1, 3, 4, 8, 9]
[0, 1, 3, 4, 8, 9]


 #### 1.9 Keyword arguments
The two `sort() /sort!()` functions have optional arguments, so called __keyword arguments__. These arguments are given by providing their respective keyword and always have a default value. In contrast to positional arguments their position does not matter. One important keyword argument for the `sort` function is `rev` which means reversed order. This can be true or false, with the default value being false.  

In [85]:
println(sort(array2,rev = true))

[9, 8, 4, 3, 1, 0]


In [86]:
## position of keyword argument does not matter: 
sort(array2,rev = true) == sort(rev = true,array2) 

true

Note: Even though the position of keyword arguments does not matter, it is common practice to provide them after all positional arguments. So always try to write : 
``` julia
func1( a,b,c, rev = true, hans = 10, color = "green")
```
instead of :
``` julia
func1( hans = 10, a,b,color = "green",c, rev = true)
```
as the second variant becomes very confusing very fast :). 



When you take a look at the offical documentation for sort (by typing `?sort` or on to the respective [webpage](https://docs.julialang.org/en/v1/base/sort/)), you can see that `sort` has overall 5 keyword arguments. One of these 5 keyword arguments is called `by`. According to the documention  "The by keyword lets you provide a custom function that will be applied to each element before comparison" . The question is now how do you provide a custom function ? This leads you smoothly to the next big section in this chapter:  How to write your own function.

### 2. Self written functions

There are three ways to define a function in Julia. 
The quickest and dirtiest way is to use the `->` operator:

In [6]:
firstfunc = x-> x^2

#7 (generic function with 1 method)

This is a function with the identifier `firstfunc` that operates on the input argument x and raises x to the power of 2 and returns the new value. 

There is also another, more mathematical inspired way to define a function in one line by using the `identifier(argument) = operation ` syntax.

In [7]:
secondfunc(x) = x^3
#arguments can also be empty
thirdfunc() = rand(1:10)
#also multiple arguments are possible
fourthfunc(t,u) = t*u +4

fourthfunc (generic function with 1 method)

We can call these functions by their identifier together with the right number of arguments. 

In [8]:
println(firstfunc(10))
println(secondfunc(3))
println(thirdfunc())
println(fourthfunc(2,5))

100
27
1
14


#### 2.1 Anonymous functions

In [9]:
x-> x^2

#9 (generic function with 1 method)

With the `->` syntax you can even omit the identifier. But why would you define a function without an identifier so cannot even call it ?  
These so called anonymous functions are very useful, when they are used as an argument to another function

The previously mentioned `sort` function is such a function, where an anonymous function can be used as keyword argument (`by = function()`).  

In [14]:
println(sort( ["bbb","aaaaaaaaa","cccccc"],by = x->length(x)))

["bbb", "cccccc", "aaaaaaaaa"]


##### 2.1.1 Map

The map function is another function that takes a function as an argument. Addtionally a collection is needed as the second positional arguments. The function is then applied to all elements of the collection. 

In [15]:
println(map(firstfunc,collect(1:10)))
# whe could also use the . notation to achieve the same
println(firstfunc.(collect(1:10)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


As you have seen above, it is also possible to apply a function to every element of a collection by using the previously shown `.` notation for operator broadcasting like `.+`. But the big advantage of the `map` function compared to the `.` notation is that you can define an anonymous function right in place.  

In [16]:
map(x->x^3+x^2+x,collect(1:10))

10-element Vector{Int64}:
    3
   14
   39
   84
  155
  258
  399
  584
  819
 1110

We can also define quite complex functions with the `->` notation. 

In [17]:
map(x->if x%3 == 0 x^3+x^2+x  elseif x%2 == 0 x =x^4 else x = 0  end,collect(1:10))

10-element Vector{Int64}:
     0
    16
    39
   256
     0
   258
     0
  4096
   819
 10000

But as seen in the cell above, it can get messy very fast when a  bigger function is defined in one line with the  `->` syntax. The same is also true for the `identifier(argument) = operation ` syntax. 

### 2.2 Complex functions

When you want to define big and complex functions you should use the third and most powerful way to define functions:
``` julia
function identifier(arguments,...)
    
    operations...
    
    return result,...
    
end
```



This way you can define a function that adds two numbers together, but only if the two numbers are even. If one or both numbers aren't even an error is printed and 0 is returned.

In [18]:
function add_only_even(num1,num2)
    
    if num1%2 ==0 && num2%2 ==0
        return num1*num2
    else
        println("ERROR ERROR ERROR")
        return 0
    end
end

add_only_even (generic function with 1 method)

In [19]:
add_only_even(2,4)

8

In [20]:
add_only_even(2,5)

ERROR ERROR ERROR


0

With this syntax, it is possible to modify the return value. For example, you don't need return aynthing. 

The function below makes the elements of the input array smaller, if they exceeds a given max size.  

In [22]:
function make_elements_smaller!(vector,max_size)
    for i in 1:length(vector)
        if vector[i] > max_size
            vector[i] = max_size
        end
    end
end    

make_elements_smaller! (generic function with 1 method)

As you should always follow the syntax convention regarding mutating and non mutation functions, the function name ends with a `!`.  

In [23]:
test_vec = rand(1:10,10)

10-element Vector{Int64}:
 3
 3
 5
 1
 8
 7
 9
 8
 7
 4

In [24]:
#no return value
make_elements_smaller!(test_vec,5)

In [25]:
test_vec

10-element Vector{Int64}:
 3
 3
 5
 1
 5
 5
 5
 5
 5
 4

The original test_vec has been changed.

#### 2.3 Keyword arguments in own functions. 
Keyword arguments offer a possibility to provide function arguments with a default value. The argument is replaced by a keyword and a default value like `keyword = default`. Keyword arguments have to be positioned after normal arguments with an `;`. The function can then be called either without the keyword argument, in which case the default value is chosen, or with explicit specification of the keyword arguments.

Note: In the documentations of many programming languages/packages, it is common to use the abbreviation `args` for positional arguments and `kwargs` for keyword arguments.  

In [26]:
function make_elements_smaller2!(vector;max_size = 5)
    for i in 1:length(vector)
        if vector[i] > max_size
            vector[i] = max_size
        end
    end
end    

make_elements_smaller2! (generic function with 1 method)

In [31]:
test_vec_2 = rand(1:10,10)
test_vec_3 = rand(1:100,10) 

10-element Vector{Int64}:
 100
  79
  73
   7
  91
  63
  52
  79
  40
  42

In [32]:
#now we can either use the default value 5 of the keyword argument or change the value by using the keyword. 
make_elements_smaller2!(test_vec_2)
make_elements_smaller2!(test_vec_3, max_size = 50)

In [33]:
test_vec_2

10-element Vector{Int64}:
 5
 1
 4
 5
 5
 5
 2
 3
 2
 3

In [34]:
test_vec_3

10-element Vector{Int64}:
 50
 50
 50
  7
 50
 50
 50
 50
 40
 42

#### 2.4 Scope of functions

Similar to loops, functions also create local scopes. Variables that are created within a function do not exist outside a function. The only way, to make a local variable inside a function visible to the outside, is by returning its value and assinging it to a new variable. 

In [67]:
function hans_peter()
    c1 = "Hans Peter"
end

hans_peter (generic function with 1 method)

In [61]:
hans_peter()
c1

LoadError: UndefVarError: c1 not defined

The variable c1 does not exist outside the function `hans_peter()`. 

In [71]:
function hans_peter2()
    c2 = "Hans Peter"
    return c2
end

hans_peter2 (generic function with 1 method)

In [72]:
c2_outside = hans_peter2()
c2_outside

"Hans Peter"

`c2_outside` holds now the value of c2. 


## Exercises:
Execute the following cell, to create the variables `a_1` - `a_4. `

In [74]:
a_1=[10, 39, 34, 35, 20, 32,  3,  9, 29, 35,  0, 27, 36, 40, 33,  5, 12, 24, 11, 50,  1,  7, 14, 22,  9]
a_2=[15,  2, 11, 16, 14,  1, 12, 14,  3,  7,  0,  4,  6, 13, 18, 19,  3,  9, 15, 16,  0, 19, 12, 13, 13]
a_3=[   4,   5,   1,   6,  3,  -3,  -6,  -1, -5,   -4]
a_4=["lizard","cat","mouse","bird","butterfly"];

### <p style='color: green'>easy</p>
1. Check all arrays for their length, print it and save the length of `a_1` in a variable.

2. Find the minimum and maximum of `a_1` and `a_3`, save them in variables .


3. Print the sentence: `"A_1 is x elements long. Its maximum is x and its minimum y."` In place of `x` and `y` add the actual values. Use your saved values.

4. Sort `a_1` and `a_4`.

### <p style='color: orange'>medium</p>


5. You might have used `1:(length(array1))` in one of your loops, there is a better solution for this task. Search for the function `enumerate()`. Familiarize yourself with this function and use it to improve the following code:
````Julia
hansus = [1,5,8,2,7,8,3,2,8,2,9,7,4]
for i in 1:(length(hansus))
       println("The element with index $(i) is $(hansus[i])")
end
````

6. Write & execute a function that take a number as argument multiplies it by `10` and prints the result.   

7. Write & execute a function that asks to input a number, multiplies it by `10` and prints the result. The function should ask for more input till you type in: `stop`.

Hint: If you are struggling with that problem, take a look at the number guesser in the first jupyter notebook called "Julia_Notebooks".   

8. Install the package `Distributions` so that you are able to execute the following cell. What is the difference between `rand()` and `rand(Uniform(-1,1))`?

In [75]:
using Distributions

9. Use the `scatter(x,y)` function from the `CairoMakie` ploting package and make a scatter plot with the created values for x and y below. 


In [78]:
x = collect(1:100)
y = [ (x^1.2+x*0.5rand(Uniform(-1,1))+rand(Uniform(-1,1)*5)) for x in 1:100];

Hint: The `;` at the end of the last line surpresses the output of the last variable in a cell. 

10. Add a line plot to your scatter plot with the `lines!` function that plots x against y_truth.

Hint: The `lines!()` function adds a line to the last used plot, but does not give an output. If you want an output you should give your scatter plot (created by `scatter()`) a name and call it after it was modified.

In [77]:
y_truth = [ x^1.2 for x in 1:100];

### <p style='color: red'>hard</p>


11. Now you have a plot containing the measured data and the ground truth but not an error.  Take a look at the documentation of [Makies errorbar](https://makie.juliaplots.org/stable/examples/plotting_functions/errorbars/) and add errorbars to every plotted point of the measured data with the mutating `errorbar!()` function.  



In [79]:
y_error = [0.5*x+5 for x in 1:100];

12. Read the section of the Julia documentation regarding [Varargs Functions](https://docs.julialang.org/en/v1/manual/functions/#Varargs-Functions). Write & execute your own function with variable arguments. The function should perform various calculations:
- It should take two numbers and any count of additional numbers
- It should sum up all arguments
- A switch should allow to instead multiply all arguments.
- If less then 2 numbers are provided an error message should be provided

13. Write & execute a function, that processes an array. The function should test if the array is filled with numbers or strings.
    - If the array contains only one data type, the appropriate function should be used: 
        - If it is a array of numbers, it should display the minimum and maximum
        - If it is a array of strings, sort it by length.
     - If the array contains both numbers and strings (or anything else) an error message should be displayed.