## 2. Datatypes

###  Sample Solutions 

### <p style='color: green'>easy</p>

#### Exercise 1 
Perform various calculations. Add, subtract, divide, multiply, exponentiate. Use integers and floats.

#### Solution 1 

In [33]:
3+3^3

30

In [34]:
5.10/2*-4

-10.2

#### Exercise 2 
 Assign values to variables and perform calculations using the variables.


In [35]:
hans = 3
dieter = 4.3436
egon = 2.1

hans^egon/dieter


2.3126228396503223

#### Exercise 3
Create two strings and assign them to the variables `string1` and `string2`. Print both, separated by a blank space.

#### Solution 3 

In [36]:
string1 = "hello my"
string2 = "beloved friend"

println(string1, " ", string2)

hello my beloved friend


#### Exercise 4
Only print the first three symbols of `string1`.

#### Solution 4

In [37]:
println(string1[1:3])

hel


#### Exercise 5
Only print every second symbol of `string2`.

#### Solution 5

In [38]:
println(string2[2:2:end])

eoe red


#### Exercise 6
Create the following arrays:

```julia
array1 = [1, "Hello", 3, "World!", 5]
array2 = [3/7, 4/9, 27/64]
array3 = [6, 7, 8]
```


#### Solution 6

In [39]:
array1 = [1, "Hello", 3, "World!", 5]
array2 = [3/7, 4/9, 27/64]
array3 = [6, 7, 8]
tuple4 = (3,1,1)

(3, 1, 1)

#### Exercise 7
Print `'Hello World!'` out of `array1` using the `[]`-operator.

#### Solution 7

In [40]:
println(array1[2], " ", array1[4])

Hello World!


#### Exercise 8
Change `'Hello'` to `2` and `'World!'` to `4` in `array1`.

#### Solution 8

In [41]:
array1[2] = 2
array1[4] = 4
array1

5-element Vector{Any}:
 1
 2
 3
 4
 5

#### Exercise 9
Append `array3` and `array1` and call the result `array4`.

#### Solution 9

In [42]:
array4 = append!(array1,array3)

8-element Vector{Any}:
 1
 2
 3
 4
 5
 6
 7
 8

#### Exercise 10
Make a copy of `array4` named `array4_2` using the `[]`-operator.

#### Solution 10

In [43]:
array4_2 = array4[1:end]
#or we can omitte the start stop values completely when they are at there default values of 1 and end
array4_2 = array4[:]

8-element Vector{Any}:
 1
 2
 3
 4
 5
 6
 7
 8

#### Exercise 11
Delete the second element from `array4_2`.

#### Solution 11


In [44]:
deleteat!(array4_2,2)

7-element Vector{Any}:
 1
 3
 4
 5
 6
 7
 8

#### Exercise 12
Test if `27/63` is in `array2`.

#### Solution 12

In [45]:
27/64 in array2

true

#### Exercise 13
Test if `2/5` is in `array2`.

#### Solution 13

In [46]:
2/5 in array2

false

#### Exercise 14
Test if `"Hello"` is in `array1`.

#### Solution 14

In [47]:
"Hello" in array1

false

#### Exercise 15
 Slice `[3,4,5,6]` out of `array4` and call the new array `array5`.

#### Solution 15

In [48]:
println(array4)
array5 = array4[3:6]

Any[1, 2, 3, 4, 5, 6, 7, 8]


4-element Vector{Any}:
 3
 4
 5
 6

#### Exercise 16 
Multiply `array5` with an integer number, assign the result to a new variable called `array6` and print out its length.

#### Solution 16

In [49]:
array6 = array5 *3

println(length(array6))

println(array6)

4
[9, 12, 15, 18]


#### Exercise 17
Make a dictionary `dict1` with the keys `"House"`, `"Garden"` and `7` with three values for each key in the form of lists.

#### Solution 17

In [50]:
dict1 = Dict("House" =>["big", "small"], "Garden" =>["green", "dry","earth"],7 => [7.0,7,"seven"])

Dict{Any, Vector} with 3 entries:
  7        => Any[7.0, 7, "seven"]
  "Garden" => ["green", "dry", "earth"]
  "House"  => ["big", "small"]

#### Exercise 18
Add another key to `dict1` with some values.

#### Solution 18

In [51]:
dict1["beautiful"] = ["Hans", "Dieter","Egon"]

3-element Vector{String}:
 "Hans"
 "Dieter"
 "Egon"

In [52]:
println(dict1["Garden"])

["green", "dry", "earth"]


#### Exercise 19
Create a matrix named ``mat1`` and multiply it with ``array5``, name the result ``mat_array``. 
Hint: The matrix has to be of the right size to make this work. If you need some refreshment of your math skills  click [here](https://www.varsitytutors.com/hotmath/hotmath_help/topics/multiplying-vector-by-a-matrix).
#### Solution 19

In [53]:
println(length(array5))
# Matrix has to have 4 colums
mat1 = ones(5,4)
mat_array = mat1*array5

4


5-element Vector{Any}:
 18.0
 18.0
 18.0
 18.0
 18.0

### <p style='color: orange'>medium</p>

#### Exercise 20
Create a new array called `mixture` which elements are the elementwise sums of `array3` and `tuple4`.  

#### Solution 20

In [54]:
tuple4

(3, 1, 1)

In [55]:
mixture = array3 + collect(tuple4)

3-element Vector{Int64}:
 9
 8
 9

In [56]:
# as array3 and tuple4 both have the same size,
# the . is not neccessary but can be used anyway
# in this case the collect can be omitted, as the . deconstructs tuple4 into 
# single Int64 values before the calculation
mixture_dot = array3 .+ tuple4

3-element Vector{Int64}:
 9
 8
 9

#### Exercise 21
Reverse the order of `array4` and print it.

#### Solution 21

In [57]:
println(array4)
array4 = array4[end:-1:1]

Any[1, 2, 3, 4, 5, 6, 7, 8]


8-element Vector{Any}:
 8
 7
 6
 5
 4
 3
 2
 1

You could also use the `reverse()` function.


In [58]:
array4_1 = reverse(array4)

8-element Vector{Any}:
 1
 2
 3
 4
 5
 6
 7
 8

#### Exercise 22
21. Create `array7` and `array8` with `[1,2,3]`. Append `[5,6,7]` to `array7` and push `array8` with `5,6 and 7`. Compare `array7` and `array_8`.

#### Solution 22

In [59]:
array_7 = [1,2,3]
array_8 = [1,2,3]
append!(array_7,[5,6,7])
push!(array_8,5,6,7) 

println(array_7)
println(array_8)
array_7 == array_8

[1, 2, 3, 5, 6, 7]
[1, 2, 3, 5, 6, 7]


true

#### Exercise 23
How often does `3` occur in all arrays (`array1`, `array2`, `array3`, `array4`, `array4_2`, `array5`, `array6`)?

#### Solution 23

In [60]:
# Solution 1 with only using already known stuff
counter_3 = 0
counter_3 += sum(3 .== array1)
counter_3 += sum(3 .== array2)
counter_3 += sum(3 .== array3)
counter_3 += sum(3 .== array4)
counter_3 += sum(3 .== array4_2)
counter_3 += sum(3 .== array5)
counter_3 += sum(3 .== array6)

counter_3


4

If you have used Google you might be stumbled across the count function. This function can also be used to solve this exercise in a more compact manner. 

In [61]:
longArray=append!(array1,array2,array3,array4,array4_2,array5,array6)

37-element Vector{Any}:
  1
  2
  3
  4
  5
  6
  7
  8
  0.42857142857142855
  0.4444444444444444
  0.421875
  6
  7
  ⋮
  5
  6
  7
  8
  3
  4
  5
  6
  9
 12
 15
 18

In [62]:
count(i ->(i ==3),longArray)

4